/*
* Project Name: Pavora
* Copyright (c) 2025 Nicola Rainiero
*
* This software is released under the MIT License.
* Please refer to the LICENSE file for the full license text.
*/
function testLanguage() {
  Logger.log(languageSelected());
  Logger.log(getCurrentLanguage());
  Logger.log(translate('page.title'));
  Logger.log(translate('alert.userPermission'));
}

function getCurrentLanguage() {
  // return "en"; // Imposta la lingua corrente
  return languageSelected(); // Cambia con la lingua desiderata o usa una logica dinamica
}

function translate(key, placeholders = {}) {
  const currentLanguage = getCurrentLanguage(); // Ottieni la lingua corrente
  const translations = getTranslations(); // Ottieni il dizionario di traduzioni

  if (!translations[currentLanguage]) {
    return key; // Se la lingua non esiste, restituisci la chiave
  }

  const keys = key.split('.'); // Suddividi la chiave in livelli
  let translation = translations[currentLanguage];

  for (const k of keys) {
    translation = translation?.[k]; // Naviga nel dizionario
    if (!translation) {
      return key; // Se una chiave non è trovata, restituisci la chiave originale
    }
  }

  // Sostituisci i placeholder dinamici
  Object.keys(placeholders).forEach(placeholder => {
    const regex = new RegExp(`\\{${placeholder}\\}`, 'g'); // Trova il placeholder
    translation = translation.replace(regex, placeholders[placeholder]);
  });

  return translation;
}

function getTranslations() {
  return {
    en: {
      'admin': {
        'emailAuto': 'This is an automated message regarding the following operation in the sharing calendar:<br>',
        'emailCheck': '<br><br>Please, check if it is correct,<br><b>',
        'addUser': 'Added user {user} to the online sheet',
        'allowUser': 'Allowed calendar access to:  ',
        'userPresent': 'The user {email} already has access to the calendar',
        'errorManage': 'This error occurred while managing permissions: ',
        'allowWrite': 'Allowed write access to file {file} for: ',
        'alreadyWrite': 'already has write access to {file}',
        'allowRead': 'Allowed read access to file {file} for: ',
        'alreadyRead': 'already has read access to {file}',
        'remCalendar': 'Calendar access removed for: ',
        'removeWrite': 'Removed write access to {file} for: ',
        'removeRead': 'Removed read access to {file} for: ',
        'recoverAdmin': 'RECOVERED BY ADMIN',
      },      
      'addEvent': {
        'appendLogRow': 'Date,Action,Event ID,User Email,Details',
        'logSubject': 'LogPavora_',
        'logNew': 'NEW',
        'logNewOne': 'NEW (ONE DAY EVENT)',
      },         
      'addEventPage': {
        'selectDateInfoTr': 'Select the dates for the new event, including assembly and disassembly phase:',
        'addPageTitle': 'Add an Event Page',        
        'justQorCC': 'Select at least one structure of the Exhibition Center or of the Conference Center!',
        'oneGate': 'Select at least one gate!',
        'infoOutTitle': 'N.B. These are the details you just entered:\n',
        'infoOutLabel': '(E=Event, A=Assembly, P=Preassembly, ecc.)\n\n',
        'infoOutDesc': '\nFor every day the description is this:\n',
        'infoOutWhere': '\nAnd it will take place here:\n',
        'infoOutQuest': '\n\nDo you want to create this event?',
        'timePeriodPre': 'Time period choose for the new event:',
        'eventName': 'Event Name',
        'colorCalendar': 'Color displayed in the calendar',
        'colNotSpec': 'Not defined',
        'colRed': 'Red',
        'colGreen': 'Green',
        'colLGreen': 'Light Green',
        'colLRed': 'Light Red',
        'colViolet': 'Purple',
        'isDefined': 'Event Status (Offer/Quotation, Option, Confirmed)',
        'offer': 'Offer',
        'option': 'Option',
        'confirmed': 'Confirmed',
        'chooseList': ' -- Pick an item -- ',
        'chooseYes': 'YES',
        'opzExpTitle': 'Set the Expiration Date for the Pending Event',
        'opzExpAlert': 'Remember to specify an expiration date for the pending event!',
        'opzExpDateAlert': 'The expiration date of the pending event cannot be greater than or equal to its start date!',
        'opzExpTodayAlert': 'The expiration date of the pending event must be after current!',
        'isOpen': 'Is it open to the public?',
        'selectStruc': 'Select all the structures occupied by the event from the menus below:',
        'selQcenter': 'Exhibition Center',
        'selCcenter': 'Congress Center',
        'selGService': 'Gates of Service',
        'selAreas': 'Areas fitting',
        'selParkEvent': 'Park and Gates during Event phase',
        'selOrganizer': 'Organiser',
        'placeNameOrganizer': 'Type the Organiser\'s Name',
        'eventCode': 'Event Code (optional)',
        'placeCode': 'Billing identification code',
        'typeEvent': 'Type of event',
        'refCom': 'Commercial representative',
        'refOp': 'Operational representative',
        'standFitter': 'Official Stand Fitter',
        'catering': 'Official Food Service',
        'details': 'Note about event (capacity, info, etc ... OPTIONAL)',
        'placeDetails': 'Put capacity first',
        'placeSqPax': 'mq occupied | numbero of person',        
        'vvf': 'Firefighter standby',
        'CPVLPS': 'NEEDED CC/CPVLPS',
        'mandatory': 'MANDATORY',
        'notMandatory': 'NOT MANDATORY',
        'reqByOrg': 'Required by Organiser',
        'presCRI': 'Emergency Aid Station',
        'defAllDay': 'Define the dates and times of the event for each phase (preassembly, assembly, event, disassembly):',
        'findNewTime': 'Search for the free structures in the new time period',
        'copyStruct': 'Copy the Event',
        'timeElapsed': 'Time left: ',
        'addDateBottom': 'Add a new date below this one',
        'removeDateBottom': 'Delete this date',
        'tableArray': ',,Date,Start,End,Phase',        
        'stringaArray': 'P,Preassembly,A,Assembly,E,Event,D,Disassembly,L,Work',
        'addOneEventDay': 'Add at least one event day!',        
      },      
      'alert': {
        'userPermission': '{user} does not have the permission!',
        'errorMessage': 'An error occured, please try again.',
      },
      'alertHtml': {
        'messageDate': 'The end date must be later than the initial date!',
      },
      'hourMenuPage': {
        'space': 'Spaces:',
        'eventAt': 'Daily events scheduled for ',
        'updateAt': '\n(updated at {adesso})',
        'eventsScheduled': 'The events scheduled in the Exhibition Center are the following:\n',
        'notHourOverlap': 'The selected hours cannot overlap. Please change one of them!',
        'selectDayHour': 'Select the day and time interval for the new event, including assembly and disassembly phase:',
        'selectDay': 'One Day Event',
        'startHourTr': 'Starting time',
        'endHourTr': 'Ending time',
        'extraTime': 'The event must not exceed one day',    
        'selecDay4edit': 'Choose the day on which the event you want to modify or delete takes place',
        'selecDayInt': 'Select the day of interest:',
        'selecTimeInt': 'Select the time interval:',        
        'fiftMin': '15 minutes',
        'therMin': '30 minutes',
        'sixMin': '60 minutes',        
      },      
      'main': {
        'logCreation': 'Date,ActionID,Event,Email User,Details',
        'lastOnline': 'Last Online',
        'logCreation': 'Date,ActionID,Event,Email User,Details',
        'instruction': 'Use the sidebar on the right ',
        'user': 'User', // Mantain the same word in eveny language
        'email': 'E-mail',
        'lastOnline': 'Last time online',
        'specialEvent': 'Dynamic Events Manager',
        'addEventPageStart': 'Set the time period for the event',
        'modifyEventPage': 'Edit, copy or delete an event',
        'viewCalendarPage': 'View events on a Gantt-like chart',
        'viewDaySlidePage': 'View daily events on a schematic plan',
        'viewListPage': 'View events in a report format',
        'viewMSRPage': 'View daily events',
        'addAskMSRPage': 'Specify the hours for the daily event',
        'editAskMSRPage': 'Edit a daily event',
      },
      'menu': {
        'title': 'Pavora Menu',
        'completeMenu': 'Reload the sidebar',
        'specialEvent': 'Event Management',
        'specialDailyEvent': 'Daily Room Management',
        'addEvent': 'Create an event',
        'modifyEvent': 'Edit an event',
        'viewCalendar': 'View events on a Gantt-like chart',
        'viewDailyCalendar': 'View daily events by a plan',
        'viewListCalendar': 'View events in a report format',
        'manageAccess': 'Manage User Permission (only Admin)',
        'downXls': 'Click here to download XLSX file',
        'saveXls': 'Save to Excel',
      },
      'modifyEvent': {
        'usedStruct': 'The structures occupied are mentioned in the note.',
        'noUsedStruct': 'All the seats are available.',
        'editDelEvent': 'Edit or delete an Event',
        'emptyCell': 'The cell is empty, select another one.',
        'noEventDate': 'In this time interval I cannot find the selected event. Please check and update dates in the menu.',
        'warEventDel': 'For the event with ID={eventId}, will be deleted the following items:\n \n',
        'noEventFound' : 'No event found for {note}',
        'confirmYN': 'Do you want to proceed with cancellation?',
        'delRoomsOK': 'DELETED (ONE DAY EVENT)',
        'delOK': 'DELETED',
        'delOKMessage': 'Events successfully deleted.',
        'waitSomeTime': 'Please wait a few moments and try again.',
        'delNOMessage': 'Cancellation undone.',
        'confModTitle': 'Are you sure you want to replace this list of daily events?',
        'logCancMod': 'DELETED PRE EDIT',
        'logCancModOne': 'DELETED PRE EDIT (ONE DAY EVENT)',
        'logEditMod': 'EDITED',
        'opNOMessage': 'Procedure cancelled.',
      },
      'modifyPageAsk': {
        'selectTimeEvent': 'Select the time interval to search for the event you want to modify or delete:',
        'changeTime': 'Change time interval',
        'posClickFind': 'In the sheet on the left, select a cell of the event you are looking for and then press the button below:',
        'click2Find': 'Click to modify, copy or delete\nthe selected event',
        'useMinusButton': 'If the searched interval time is less than the initial one, just delete the days with the "-" button in the table at the bottom',
        'deleteEvent': 'Delete it',
        'editEvent': 'Edit it',
        'changeEvent': 'Change Event',
        'dateChangeEvent': 'Duration of the event to modify or delete:',
        'displayIDCode': 'Event identification code',
        'nameOrEvent': 'Event original name',
        'comeBack': 'CANCEL AND BACK',        
      },     
      'page': {
        'title': 'Page Title',
        'subtitle': 'Subtitle of the page',
      },
      'planPage': {
        'dailySpace': 'Daily Allocation Plan (',
        'threeDayAbb': 'Sun,Mon,Thu,Wed,Tue,Fri,Sat',
        'alertMuchDays': 'To stay within the usage limits of Google Slides, it is recommended to request a maximum of 2 days.',
        'intSelPeriod': 'Select the period of interest (1 day recommended, maximum 2 days):',
        'whatView': 'Choose what to view:',
        'editSlide': 'Would you like to edit it in Google Slides?',
        'slideFile': '_DailyAllocation_',
        'slideFileAlert': 'The file is available here: ',
      },      
      'sidebar': {
        'specialEvent': 'Event Management',
        'addEvent': 'Add an event',
        'editEvent': 'Edit, copy or delete an event',
        'addDailyEvent': 'Add a daily event',
        'editDailyEvent': 'Edit or delete a daily event',
        'showEventGantt': 'View events on a Gantt-like chart',
        'showDailyEvent': 'View daily events',
        'showPlanEvent': 'View daily events on a plan',
        'showReportEvent': 'View events in an editable report',
      },
      'specialEvent': {
        'newSheet': 'Sheet created at ',
        'filter': 'Search Filters',
        'info': 'Below you can add or edit the events listed in the sheet on the left, previously searched through the \'Search Filters\' menu. Just select the cells with the structures and dates to add an event, or a single cell to edit or delete the entire event:',
        'tip' : 'An update to the diagram on the left is suggested',
        'events' : 'Events:',
        'date' : 'Date',
        'structure' : 'Structure',
        'confirmed' : 'CONFIRMED',
        'optionated' : 'PENDING',
        'offer' : 'OFFER',
        'work' : 'WORK',
        'concurrent' : 'CONCURRENT',
        'newEvent': 'New event being defined',
        'selectOneFirst' : 'Select at least one cell before continuing',
        'selectCellRowSec' : 'Select cells that contain valid dates in row 2',
        'noNoteCell' : 'No note found in the selected cell',
        'noIdFound' : 'No ID found in the note',
        'selectValidColumn' : 'Select at least one valid column',
        'selectCellRowfive' : 'Select cells that contain valid dates in row 5',
      },
      'viewCalendar': {
        'firstCell': 'Chart of events',
        'secondCell': 'scheduled at',
        'mainCell': 'Pavora District',
        'date': 'Date:',
        'structures': 'Structures:',
        'months': 'January, February, March, April, May, June, July, August, September, October, November, December',
        'days': 'S, M, T, W, T, F, S',
        'eventsList': 'EVENTS & WORKS LIST:',
        'numberEvent': 'NUMBER (EVENT DAY)',
        'assOrDisass': '(ASSEMBLY OR DISASSEMBLY)',
        'preAss': '(PREASSEMBLY)',
        'numberOpz': 'NUMBER (PENDING EVENT DAY)',
        'numberOff': 'NUMBER (OFFER EVENT DAY)',
        'moreEvents': 'CONCURRENT EVENTS',
        'letterWork': 'LETTER\n(WORKING DAY)',
        'where': '\nWhere:\n',
      },
      'viewCalendarPage': {
        'periodTr': 'Select the time interval:',
        'startDateTr': 'Start date',
        'endDateTr': 'End date',
        'findStuctTr': 'If you want to limit your search to some structures, select them from here:',
        'sideQTr': 'Side Exhibition Center',
        'sideCCTr': 'Side Congress Center',        
        'findWordTr': 'If you want to limit your search to a keyword (N.B. +word shows only that one, -word shows everything except that word), write it here:',
        'insertWordTr': 'Insert a keyword',
        'goButtonTr': 'Go on',
        'goUpdateTr': 'UPDATE',
        'delAllFormTr': 'Clear the form',
        'waitTr': 'Wait...',
        'stats' : 'Click below to obtain the stats in the period at the left:',
        'statsColumns' : 'Stats per days',
        'statsRows' : 'Stats per structure',
        'wrongSheet' : 'The sheet has no correct data, generate again!',
      },
      'viewList': {
        'whatSee': 'Choose the phase(s) you want to view:',
        'labelP': 'Preassembly',
        'labelA': 'Assembly',
        'labelE': 'Event',
        'labelD': 'Disassembly',
        'labelW': 'Word',
        'whichMode': 'Events Grouping Mode:',
        'grouped': 'Grouped by Name and Date',
        'listed': 'Listed Daily',
        'editMenu': 'You can edit the events grouped in the sheet on the left and then update them one by one using the buttons below:',
        'upGeneral': 'Update the general information of the selected event',
        'upSpec': 'Update the times and/or structures of the selected event',
        'newEvent': 'Add a new event in the selected cells',
        'delEvent': 'Delete the entire selected event',
        'noPermission': 'You are not allowed to view these buttons.',
        'alertEdit': 'To edit it you must view the events as \'Grouped by Name and Date\'',
        'alertOldEdit': 'The {name} event was added with the old system, you need to edit it from the main menu command',
        'eventsFrom': 'Events scheduled from ',
        'eventsTo': ' to ',
        'updateAt': '\n(update to ',
        'headerAggr': 'Start Date,Event Name,Code,Structure(s),∑mq,∑people,Details,Duration ({myarr}),Commercial rep.,Operational rep.,Organiser,Fitter,Catering,Type,Status,Pubblic?,Fire Dep.,First Aid,Num. AE,Pending Expiration Date',
        'headerList': 'Start Date,Event Name,Phase,Start Hour,End Hour,Structure(s),∑mq,∑people,Details,Type,Status,Pubblic?,Fire Dep.,First Aid,Num. AE',
        'updateOf': 'Update of ',
        'okTo': '\n\nWould you like to update it?',
        'diffFound': 'Changes found:\n',
        'noDiffFound': 'No changes found.',
        'titleChanges': 'Event Name,Status,Pubblic?,Exhibition Center,Congress Center,Gate(s),Area(s),Park(s),Fitter,Fire Dep.,First Aid,Commercial Rep.,Details,idEvent,Phase,date,startTime,endTime,startTimeUTC,endTimeUTC,location,Operational Rep.,Organiser,type,color,Catering,Code Event,Pending Expiration Date',
        'okEditSpecific': 'Confirm changes to dates and structures',
        'yesEditSpecific': 'Are you sure you want to go to the menu to edit the dates and/or the structures for the {name} event?',
      },      
    },
    it: {
      'admin': {
        'emailAuto': 'Questo messaggio viene inviato in automatico,<br>perché è stata eseguita questa operazione nel calendario condiviso:<br>',
        'emailCheck': '<br><br>Per cortesia, verifica se è corretta,<br><b>',
        'addUser': 'Aggiunto l\'utente {user} al foglio online',
        'allowUser': 'Concesso accesso al calendario a:  ',
        'userPresent': 'L\'utente {email} ha già accesso al calendario',
        'errorManage': 'Si è presentato questo errore durante la gestione dei permessi: ',
        'allowWrite': 'Concesso accesso di scrittura a {file} per: ',
        'alreadyWrite': 'ha già accesso di scrittura a {file}',
        'allowRead': 'Concesso accesso di lettura a {file} per: ',
        'alreadRead': 'ha già accesso di lettura a {file}',
        'remCalendar': 'Accesso al calendario rimosso per: ',
        'removeWrite': 'Rimosso accesso di scrittura a {file} per: ',
        'removeRead': 'Rimosso accesso di lettura a {file} per: ',
        'recoverAdmin': 'RIPRISTINATO DA ADMIN',
      },      
      'addEvent': {
        'appendLogRow': 'Data,Azione,Event ID,Email Utente,Dettagli',
        'logSubject': 'LogPavora_',
        'logNew': 'NUOVO',
        'logNewOne': 'NUOVO (EVENTO UN GIORNO)',
      },        
      'addEventPage': {
        'selectDateInfoTr': 'Seleziona le date di svolgimento per il nuovo evento, comprensive di allestimento e disallestimento:',
        'justQorCC': 'Seleziona almeno una struttura del quartiere o sala del Centro Congressi!',
        'addPageTitle': 'Aggiungi un evento',        
        'oneGate': 'Seleziona almeno un cancello o ingresso!',
        'infoOutTitle': 'N.B. Questi sono i dati che hai appena inserito:\n',
        'infoOutLabel': '(E=Evento, A=Allestimento, P=Prenotato, ecc.)\n\n',
        'infoOutDesc': '\nPer tutti i giorni la descrizione è questa:\n',
        'infoOutWhere': '\nE si svolgerà qui:\n',
        'infoOutQuest': '\n\nVuoi procedere con la creazione dell\'evento?',
        'timePeriodPre': 'Periodo scelto per il nuovo evento:',
        'eventName': 'Nome dell\'evento',
        'colorCalendar': 'Colore visualizzato nel calendario',
        'colNotSpec': 'Non specificato',
        'colRed': 'Rosso',
        'colGreen': 'Verde',
        'colLGreen': 'Verde chiaro',
        'colLRed': 'Rosso chiaro',
        'colViolet': 'Viola',
        'isDefined': 'Stato dell\'Evento (Offerta, Opzione, Confermato)',
        'offer': 'Offerta',
        'option': 'Opzione',
        'confirmed': 'Confermato',
        'chooseList': ' -- scegli dall\'elenco -- ',
        'chooseYes': 'SI',
        'opzExpTitle': 'Imposta la data di scadenza per l\'evento in sospeso',
        'opzExpAlert': 'Ricorda di specificare una data di scadenza per l\'opzione!',
        'opzExpDateAlert': 'La scadenza dell\'evento opzionato non può essere maggiore o uguale alla data di inizio dell\'evento!',
        'opzExpTodayAlert': 'La data di scadenza dell\'evento opzionato deve essere successiva a quella corrente.',        
        'isOpen': 'È aperto al pubblico?',
        'selectStruc': 'Seleziona tutte le strutture occupate dai seguenti menu:',
        'selQcenter': 'Quartiere',
        'selCcenter': 'Centro Congressi',
        'selGService': 'Cancelli di servizio',
        'selAreas': 'Aree allestite',
        'selParkEvent': 'Parcheggi e Cancelli in fase di evento',
        'selOrganizer': 'Organizzatore',
        'placeNameOrganizer': 'Inserisci il nome dell\'Organizzatore',
        'eventCode': 'Codice Evento (facoltativo)',
        'placeCode': 'Codice identificativo per fatturazione',
        'typeEvent': 'Tipologia di evento',
        'refCom': 'Referente commerciale',
        'refOp': 'Referente operativo',
        'standFitter': 'Allestitore ufficiale',
        'catering': 'Catering ufficiale',
        'details': 'Note (capienza, info, ecc ... è facoltativo)',
        'placeDetails': 'Prima la capienza',
        'placeSqPax': 'mq occupati | persone',
        'vvf': 'Presidio VVF',
        'CPVLPS': 'NECESSARIA CC/CPVLPS',
        'mandatory': 'NECESSARIO',
        'notMandatory': 'NON NECESSARIO',
        'reqByOrg': 'Richiesto dall\'Organizzatore',
        'presCRI': 'Presidio Primo Soccorso',
        'defAllDay': 'Definisci i giorni e gli orari dell\'evento nelle varie fasi (prenotazione, allestimento, evento, disallestimento):',
        'findNewTime': 'Modifica le date', //Cerca le strutture libere nel nuovo intervallo
        'copyStruct': 'Copia l\'evento',
        'timeElapsed': 'Tempo rimasto: ',
        'addDateBottom': 'Aggiungi una nuova data sotto a questa',
        'removeDateBottom': 'Rimuovi questa data',
        'tableArray': ',,Data,Inizio,Fine,Fase',        
        'stringaArray': 'P,Preallestimento,A,Allestimento,E,Evento,D,Disallestimento,L,Lavoro',
        'addOneEventDay': 'Aggiungi almeno un giorno di evento!',              
      },      
      'alert': {
        'userPermission': '{user} non ha il permesso!',
        'errorMessage': 'Si è verificato questo errore: {error}.\nRiprova per cortesia.',
      },
      'alertHtml': {
        'messageDate': 'La data finale deve essere successiva a quella iniziale!',
      },
      'hourMenuPage': {
        'space': 'Sale:',
        'eventAt': 'Eventi giornalieri programmati per ',
        'updateAt': '\n(aggiornati al {adesso})',
        'eventsScheduled': 'Gli eventi presenti in quartiere sono i seguenti:\n',
        'notHourOverlap': 'Le ore scelte non possono coincidere, devi cambiarne una delle due!!',
        'selectDayHour': 'Seleziona il giorno e l\'intevallo di tempo per il nuovo evento, comprensivo di allestimento, disallestimento e pulizia:',
        'selectDay': 'Giorno unico di evento',
        'startHourTr': 'Orario d\'inizio',
        'endHourTr': 'Orario di fine',
        'extraTime': 'L\'evento non può durare più di un giorno!',
        'selecDay4edit': 'Scegli il giorno in cui si svolge l\'evento da modificare o cancellare',
        'selecDayInt': 'Seleziona il giorno di interesse:',
        'selecTimeInt': 'Selezione l\'intervallo di tempo:',
        'fiftMin': '15 minuti',
        'therMin': '30 minuti',
        'sixMin': '60 minuti',        
      },      
      'main': {
        'logCreation': 'Date,ActionID,Event,Email User,Details',        
        'instruction': 'Usa la barra laterale sulla destra',
        'user': 'User', // Mantain the same word in eveny language
        'email': 'e-mail',
        'lastOnline': 'Ultima volta online',
        'specialEvent': 'Gestione dinamica degli eventi',
        'addEventPageStart': 'Selezione il periodo dell\'evento',
        'modifyEventPage': 'Modifica, copia  o concella un evento',
        'viewCalendarPage': 'Visualizza gli eventi in un Gantt adattato',
        'viewDaySlidePage': 'Visualizza la planimetria giornaliera',
        'viewListPage': 'Visualizza gli eventi in un report editabile',
        'viewMSRPage': 'Visualizza gli eventi giornalieri',
        'addAskMSRPage': 'Specifica gli orari per l\'evento giornaliero',
        'editAskMSRPage': 'Modifica un evento giornaliero',
      },
      'menu': {
        'title': 'Menu di Pavora',
        'completeMenu': 'Ricarica la barra laterale',
        'specialEvent': 'Gestione eventi',
        'specialDailyEvent': 'Gestione sale giornaliere',
        'addEvent': 'Crea un evento',
        'modifyEvent': 'Modifica un evento',
        'viewCalendar': 'Visualizza gli eventi in un diagramma di Gantt adattato',
        'viewDailyCalendar': 'Visualizza gli eventi giornalieri in una planimetria',
        'viewListCalendar': 'Visualizza gli eventi in un report editabile',
        'manageAccess': 'Gestione dei permessi per gli utenti (solo Admin)',
        'downXls': 'Clicca qui per scaricare il file XLSX',
        'saveXls': 'Salva in Excel',
      },
      'modifyEvent': {
        'usedStruct': 'Le strutture occupate sono nella nota.',
        'noUsedStruct': 'Tutte le strutture sono disponibili',
        'editDelEvent': 'Modifica o cancella un Evento',
        'emptyCell': 'Nella cella selezionata non c\'è niente, posizionati in un altro punto.',
        'noEventDate': 'Nell\'intervallo di tempo indicato non trovo l\'evento selezionato. Per cortesia verifica e aggiorna le date del menu.',
        'noEventFound' : 'Nessun evento trovato per {note}',
        'warEventDel': 'Per l\'evento con ID={eventId}, stai per cancellare queste voci:\n \n',
        'confirmYN': 'Conferma la cancellazione',
        'delRoomsOK': 'CANCELLATO (EVENTO UN GIORNO)',
        'delOK': 'CANCELLATO',
        'delOKMessage': 'Eventi cancellati con successo.',
        'waitSomeTime': 'Attendi ancora qualche istante e riprova.',
        'delNOMessage': 'Cancellazione annullata.',
        'confModTitle': 'Sei sicuro di voler sostituire questa lista di eventi giornalieri?',
        'logCancMod': 'CANCELLATO PER MODIFICA',
        'logCancModOne': 'CANCELLATO PER MODIFICA (EVENTO UN GIORNO)',
        'logEditMod': 'MODIFICATO',
        'opNOMessage': 'Operazione annullata.',
      },
      'modifyPageAsk': {
        'selectTimeEvent': 'Seleziona le date per la ricerca dell\'evento da modificare o cancellare:',
        'changeTime': 'Cambia periodo',
        'posClickFind': 'Nel foglio a sinistra, seleziona una cella dell\'evento ricercato e poi clicca sul bottone qui sotto:',
        'click2Find': 'Premi per modificare, copiare o cancellare\nl\'evento selezionato',
        'useMinusButton': 'Se l\'intervallo cercato è minore di quello iniziale, basta cancellare i giorni con il bottone "-" nella tabella a fondo pagina',
        'deleteEvent': 'Cancellalo',
        'editEvent': 'Modificalo',
        'changeEvent': 'Cambia Evento',
        'dateChangeEvent': 'Durata dell\'evento da modificare o cancellare:',
        'displayIDCode': 'Codice identificativo dell\'evento',
        'nameOrEvent': 'Nome originale dell\Evento',
        'comeBack': 'Torna indietro',
      },        
      'page': {
        'title': 'Titolo della Pagina',
        'subtitle': 'Sottotitolo della pagina',
      },
      'planPage': {
        'dailySpace': 'Piano di occupazione giornaliera (',
        'threeDayAbb': 'dom,lun,mar,mer,gio,ven,sab',
        'alertMuchDays': 'Per restare entro i limiti di utilizzo di Google Slide si consiglia di richiedere al massimo 2 giorni',
        'intSelPeriod': 'Seleziona il periodo di interesse (consigliato 1 giorno, al massimo 2):',
        'whatView': 'Scegli cosa visualizzare:',
        'editSlide': 'Vuoi modficarlo in Presentazioni Google?',
        'slideFile': '_Occupazione_',
        'slideFileAlert': 'Il file lo trovi qui: ',
      },            
      'sidebar': {
        'specialEvent': 'Gestione eventi',
        'addEvent': 'Aggiungi un evento',
        'editEvent': 'Modifica, copia o cancella un evento',
        'addDailyEvent': 'Aggiungi un evento giornaliero',
        'editDailyEvent': 'Modifica un evento di un giorno',
        'showEventGantt': 'Mostra gli eventi in un diagramma',
        'showDailyEvent': 'Mostra gli eventi giornalieri',
        'showPlanEvent': 'Mostra gli eventi in una planimetria',
        'showReportEvent': 'Mostra gli eventi in una lista editabile',
      },
      'specialEvent': {
        'newSheet': 'Foglio creato alle ',
        'filter': 'Filtri di ricerca',
        'info': 'Qui sotto puoi aggiungere o modificare gli eventi presenti nel foglio a sinistra, precedentemente ricercati nel menu \'Filtri di ricerca\', basta selezionare le celle con le strutture e i giorni per aggiungere un evento o la singola cella per modificare l\'intero evento o cancellarlo:',
        'tip' : 'È vivamente raccomandato aggiornare il diagraamma sulla sinistra',
        'events' : 'Eventi:',
        'date' : 'Data',
        'structure' : 'Struttura',
        'confirmed' : 'CONFERMATI',
        'optionated' : 'OPZIONATI',
        'offer' : 'OFFERTA',
        'work' : 'LAVORI',
        'concurrent' : 'CONCORRENTI',
        'newEvent': 'Nuovo evento in fase di definizione',
        'selectOneFirst' : 'Seleziona almeno una cella prima di continuare',
        'selectCellRowSec' : 'Seleziona celle che contengano date valide nella riga 2',
        'noNoteCell' : 'Nessuna nota presente nella cella selezionata',
        'noIdFound' : 'Nessun ID trovato nella nota',
        'selectValidColumn' : 'Seleziona almeno una colonna valida',
        'selectCellRowfive' : 'Seleziona celle che contengano date valide nella riga 5',
      },
      'viewCalendar': {
        'firstCell': 'Diagramma eventi',
        'secondCell': 'in programma a',
        'mainCell': 'Pavora',
        'date': 'Data:',
        'structures': 'Strutture:',
        'months': 'Gennaio, Febbraio, Marzo, Aprile, Maggio, Giugno, Luglio, Agosto, Settembre, Ottobre, Novembre, Dicembre',
        'days': 'D, L, M, M, G, V, S',
        'eventsList': 'LISTA EVENTI E LAVORI:',
        'numberEvent': 'NUMERO (GIORNATA DI EVENTO)',
        'assOrDisass': '(ALLESTIMENTO O DISALLESTIMENTO)',
        'preAss': '(PREALLESTIMENTO)',
        'numberOpz': 'NUMERO (GIORNATA DI POSSIBILE EVENTO)',
        'numberOff': 'NUMERO (PROPOSTA/OFFERTA PER EVENTO)',
        'moreEvents': 'EVENTI CONCOMITANTI',
        'letterWork': 'LETTERA\n(GIORNATA CON LAVORAZIONI)',
        'where': '\nSi svolge in:\n',        
      },
      'viewCalendarPage': {
        'periodTr': 'Seleziona il periodo:',
        'startDateTr': 'Data iniziale',
        'endDateTr': 'Data finale',
        'findStuctTr': 'Se vuoi limitare la ricerca ad alcune strutture, selezionale da qui:',
        'sideQTr': 'Lato Quartiere',
        'sideCCTr': 'Lato Centro Congressi',        
        'findWordTr': 'Se vuoi limitare la ricerca ad una parola chiave (N.B. +parola mostra solo quella, -parola mostra tutto tranne quella parola), scrivila qui:',
        'insertWordTr': 'Inserisci la parola chiave',
        'goButtonTr': 'Procedi',
        'goUpdateTr': 'Salva e/o aggiorna',
        'delAllFormTr': 'Cancella il form',
        'waitTr': 'Attendi...',
        'stats' : 'Clicca sotto per vedere le statistiche nel periodo sulla sinistra:',
        'statsColumns' : 'Statistiche per giorno',
        'statsRows' : 'Statistiche per struttura',
        'wrongSheet' : 'Il foglio non contiene dati utili per le statistiche, rigeneralo',
        },
      'viewList': {
        'whatSee': 'Scegli quale fase/i vuoi vedere:',
        'labelP': 'Preallestimento',
        'labelA': 'Allestimento',
        'labelE': 'Evento',
        'labelD': 'Disallestimento',
        'labelW': 'Lavoro',
        'whichMode': 'Modalità di raggruppamento degli eventi:',
        'grouped': 'Uniti per nome e data',
        'listed': 'Elencati giornalmente',
        'editMenu': 'Puoi modificare gli eventi raggruppati nel foglio a sinistra e poi aggiornarne uno alla volta dai seguente pulsanti: ',
        'upGeneral': 'Aggiorna i dati generali dell\'evento selezionato',
        'upSpec': 'Modifica l\'evento', //Aggiorna orari e/o strutture dell\'evento selezionato
        'newEvent': 'Aggiungi un nuovo evento nelle celle selezionate',
        'delEvent': 'Cancella tutto l\'evento selezionato',
        'noPermission': 'Non hai i permessi per visualizzare questi bottoni.',
        'alertEdit': 'Per la modifica devi visualizzare gli eventi come \'Raggruppati per nome e data\'',
        'alertOldEdit': 'L\'evento {name} è stato inserito con il vecchio sistema, va modificato dal menu principale',
        'eventsFrom': 'Eventi a calendario dal ',
        'eventsTo': ' al ',
        'updateAt': '\n(aggiornati al ',
        'headerAggr': 'Inizio,Evento,Codice,Strutture,∑mq,∑pax,Note,Durata ({myarr}),Referente,Operation,Organizzatore,Allestitore,Catering,Tipo evento,Stato pratica,Pubblico?,VVF,CRI,Num. AE,Scadenza Opz.',
        'headerList': 'Inizio,Evento,Fase,Inizio,Fine,Strutture,∑mq,∑pax,Note,Tipo evento,Stato pratica,Pubblico,VVF,CRI,Num. AE',
        'updateOf': 'Aggiornamento di ',
        'okTo': '\n\n Vuoi lo stesso aggiornare l\'evento?',
        'diffFound': 'Differenze trovate:\n',
        'noDiffFound': 'Nessuna differenza trovata.',
        'titleChanges': 'Nome evento,Stato pratica,Aperto al pubblico?,quartiere,congress,ingressi,aree,parcheggi,Allestitore,vvf,cri?,Referente Commerciale,note,idEvent,type,data,startTime,endTime,startTimeUTC,endTimeUTC,location,Referente Operativo,Organizzatore,Tipo evento,color,Catering,Codice Amministrazione,Data scadenza',
        'okEditSpecific': 'Conferma modifica orari e strutture',
        'yesEditSpecific': 'Sei sicuro di voler passare nel menu per la modifica degli orari e/o delle strutture dell\'evento {name}?',
        },        
    },
  };
}
